# -*- coding: utf-8 -*-
"""Statistics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nx1XZ3CzGw4yPHww2gnTjEN6uKF9UgVZ
"""

# Commented out IPython magic to ensure Python compatibility.
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline

import statistics

df = pd.read_csv('/content/WAEMU_Banking.csv')

df.head()

df.tail()

df.isnull()

np.mean(df['VA'])

np.median(df['VA'])

statistics.mode(df['VA'])

sns.boxplot(df['VA'])

sns.histplot(df['VA'])

sns.histplot(df['VA'],kde=True)

sns.countplot(df['VA'])

np.percentile(df['VA'],[25,75])

